// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

library Level {
    uint256 public constant EXP_DECIMALS = 3;

    function _calcOfflineRewardPerDay(
        uint256 effort,
        uint256 level
    ) internal pure returns (uint256 reward) {
        uint256 baseRate = 4 * 10 ** EXP_DECIMALS;
        uint256 effortFactor = _getEffortFactorByLevel(level);
        bool unenoughEffort = effort < effortFactor * level;
        uint256 levelFactor = unenoughEffort
            ? ((level ** 2 * (10 - effortFactor)) / 10)
            : level ** 2;
        uint256 divFactor = 5;

        reward = (baseRate * levelFactor) / divFactor;
    }

    function _getOfflineRewardPortion(
        uint256 _duration
    ) internal pure returns (uint256 portion) {
        uint256 forDecimals = 10 ** EXP_DECIMALS;
        uint256 perDayBySecond = 86400;
        portion = (_duration * forDecimals) / perDayBySecond;
    }

    function _getEffortFactorByLevel(
        uint256 level
    ) public pure returns (uint256 effortFactor) {
        if (level < 4) effortFactor = 2;
        if (level < 8) effortFactor = 3;
        if (level < 13) effortFactor = 4;
        if (level < 19) effortFactor = 5;
        if (level < 26) effortFactor = 6;
        if (level < 30) effortFactor = 7;
    }

    // level curve is generated by the formula: ( 5000 * n^3 ) / 4 > 取 decinals 精度
    function _getCurrentLevel(
        uint256 totalExp
    ) public pure returns (uint256 level) {
        if (totalExp < 1250) level = 1;
        if (totalExp < 10000) level = 2;
        if (totalExp < 33750) level = 3;
        if (totalExp < 80000) level = 4;
        if (totalExp < 156250) level = 5;
        if (totalExp < 270000) level = 6;
        if (totalExp < 428750) level = 7;
        if (totalExp < 640000) level = 8;
        if (totalExp < 911250) level = 9;
        if (totalExp < 1215000) level = 10;
        if (totalExp < 1663750) level = 11;
        if (totalExp < 2160000) level = 12;
        if (totalExp < 2746250) level = 13;
        if (totalExp < 3430000) level = 14;
        if (totalExp < 4218750) level = 15;
        if (totalExp < 5120000) level = 16;
        if (totalExp < 6141250) level = 17;
        if (totalExp < 7290000) level = 18;
        if (totalExp < 8573750) level = 19;
        if (totalExp < 10000000) level = 20;
        if (totalExp < 11576250) level = 21;
        if (totalExp < 13310000) level = 22;
        if (totalExp < 15208750) level = 23;
        if (totalExp < 17280000) level = 24;
        if (totalExp < 19531250) level = 25;
        if (totalExp < 21970000) level = 26;
        if (totalExp < 24603750) level = 27;
        if (totalExp < 27440000) level = 28;
        if (totalExp < 30486250) level = 29;
        if (totalExp < 33750000) level = 30;
    }
}
