// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

library Level {
    uint256 public constant EXP_DECIMALS = 3;

    function _calcOfflineRewardPerDay(
        uint256 effort,
        uint256 level
    ) internal pure returns (uint256 reward) {
        uint256 baseRate = 4 * 10 ** EXP_DECIMALS;
        uint256 levelFactor = _getLevelFactor(level, effort);
        uint256 divFactor = 5;

        reward = (baseRate * levelFactor) / divFactor;
    }

    function _getLevelFactor(
        uint256 level,
        uint256 effort
    ) public pure returns (uint256 levelFactor) {
        uint256 normalLevelEffort = level ** 2;

        uint256 effortFactor = _getEffortFactorByLevel(level);
        bool unenoughEffort = effort < effortFactor * level;

        levelFactor = unenoughEffort
            ? ((normalLevelEffort * (10 - effortFactor)) / 10)
            : normalLevelEffort;

        levelFactor = level >= 3 ? levelFactor : normalLevelEffort;
    }

    function _getOfflineRewardPortion(
        uint256 _duration
    ) internal pure returns (uint256 portion) {
        uint256 forDecimals = 10 ** EXP_DECIMALS;
        portion = (_duration * forDecimals) / 3 hours;
    }

    function _getEffortFactorByLevel(
        uint256 level
    ) public pure returns (uint256) {
        if (level < 4) return 2;
        if (level < 8) return 3;
        if (level < 13) return 4;
        if (level < 19) return 5;
        if (level < 26) return 6;
        if (level < 30) return 7;
        return 7;
    }

    // level curve is generated by the formula: ( 5000 * n^3 ) / 4 > 取 decinals 精度
    function _getCurrentLevel(uint256 totalExp) public pure returns (uint256) {
        if (totalExp < 1250) return 1;
        if (totalExp < 10000) return 2;
        if (totalExp < 33750) return 3;
        if (totalExp < 80000) return 4;
        if (totalExp < 156250) return 5;
        if (totalExp < 270000) return 6;
        if (totalExp < 428750) return 7;
        if (totalExp < 640000) return 8;
        if (totalExp < 911250) return 9;
        if (totalExp < 1215000) return 10;
        if (totalExp < 1663750) return 11;
        if (totalExp < 2160000) return 12;
        if (totalExp < 2746250) return 13;
        if (totalExp < 3430000) return 14;
        if (totalExp < 4218750) return 15;
        if (totalExp < 5120000) return 16;
        if (totalExp < 6141250) return 17;
        if (totalExp < 7290000) return 18;
        if (totalExp < 8573750) return 19;
        if (totalExp < 10000000) return 20;
        if (totalExp < 11576250) return 21;
        if (totalExp < 13310000) return 22;
        if (totalExp < 15208750) return 23;
        if (totalExp < 17280000) return 24;
        if (totalExp < 19531250) return 25;
        if (totalExp < 21970000) return 26;
        if (totalExp < 24603750) return 27;
        if (totalExp < 27440000) return 28;
        if (totalExp < 30486250) return 29;
        return 30;
    }
}
