// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

contract ErrorConfig {
    // NotDitto
    error ErrorFromInteractWithNotDitto(uint256 errorCode);
    // ERC1155
    error ErrorFromErc1155(uint256 errorCode);

    enum ErrorNotDitto {
        EXCEED_MAX_NOT_DITTO_SUPPLY_PER_ADDRESS,
        NOT_ALLOW_NOT_DITTO_TO_BE_SELF_MINTED,
        NOT_OWNER_OF_THE_NFT,
        NOT_OWNER_OF_THE_NOT_DITTO,
        NOT_DITTO_IS_UNHAPPY_TO_MORPH_ZERO_ADDRESS,
        NOT_DITTO_IS_UNHAPPY_TO_MORPH_ITSELF,
        ZERO_ADDRESS_IS_NOT_AVAIABLE_OPERATOR,
        NOT_DITTO_IS_UNHAPPY_TO_MORPH_EXISTED_NFT,
        ZERO_ADDRESS_IS_NOT_AVAIABLE_OWNER,
        INVALID_IDS_AND_VALUES,
        NOT_DITTOS_ARE_UNHAPPY_TO_LEAVE_YOU_TOGETHER,
        WRONG_MINT_PRICE,
        NOT_ENOUGH_RAISE_SUPPORT_FEE,
        ALL_NOT_DITTO_HAS_PARENTS,
        NOT_DITTOS_ARE_ONLY_MINTABLE_AND_BURNABLE,
        SHOULD_ACCESS_TO_DRAW_WITH_MAX_LV_NOT_DITTO,
        ALREADY_ENGAGED_IN_THIS_DRAW
    }

    enum ErrorErc1155 {
        ZERO_ADDRESS_IS_NOT_AVAIABLE_OWNER,
        MISMATCH_ACCOUNTS_AND_IDS,
        MISTMATCH_IDS_AND_VALUES_LENGTH,
        MISMATCH_IDS_AND_AMOUNTS,
        CALLER_IS_NOT_TOKEN_OWNER_NOR_APPROVED,
        INSUFFICIENT_BALANCE_FOR_TRANSFER
    }
}
